### ISSUE TITLE
Can I run the pretrained model on a cpu?

### ISSUE THREAD

**Issue by ST2-EV** [saic-mdal/deep-landscape#10]
Is a GPU necessary to run the pre-trained models as well?

**Comment by windj007** [comment]
Yes, surely! However, this probably will be slower than running on GPU. Generating synthetic videos (i.e. only generator, no encoder and inference) should be pretty fast on CPU. Reenacting a real image is more demanding, because it requires optimization.

**Comment by ST2-EV** [comment]
oh okay thanks
