### ISSUE TITLE
When will the codes be released?

### ISSUE THREAD

**Issue by kult0922** [saic-mdal/deep-landscape#6]
I read your paper and I think that your work is really interesting, and I'd really like to see your implementation.
When will you release them?

**Comment by windj007** [comment]
Thank you for the interest in our work! We are working on making code publicly available. Prediction/inference code may become available sooner, within one or two weeks, but we also hope to release training code soon as well.

**Comment by mdork** [comment]
Any updates on the code? at least inference?

**Comment by windj007** [comment]
Thank you for your interest! We are working on it.

**Comment by windj007** [comment]
We are almost done with all code-related and legal stuff and most probably we will push the code in the beginning of the next week.
